version: '3'

services:
  webserver:
    build: node
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "3000:3000"
  
  db:
    build: postgresql
    volumes:
      - ./postgresql/psdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      POSTGRES_PASSWORD: 'password'